### ISSUE TITLE
 java.lang.RuntimeException: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by christor54** [christor54/login-facebook-google-password-firebase-android#4]
java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NullPointerException
            at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:911)
            at com.facebook.internal.Utility.queryAppSettings(Utility.java:673)
            at com.facebook.widget.LoginButton$1.doInBackground(LoginButton.java:678)
            at com.facebook.widget.LoginButton$1.doInBackground(LoginButton.java:675)

**Comment by christor54** [comment]
Take out the facebook login button fix the issue
